# Generated by Django 6.0.2 on 2026-03-12 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilesection',
            name='background_picture',
        ),
        migrations.RemoveField(
            model_name='userprofilesection',
            name='profile_picture',
        ),
    ]
