# Generated by Django 6.0.2 on 2026-03-13 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofilesection_background_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExperienceSubsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofilesection')),
            ],
        ),
        migrations.CreateModel(
            name='UserTechnicalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofilesection')),
            ],
            options={
                'db_table': 'technical_skills',
            },
        ),
        migrations.CreateModel(
            name='UserTechnicalSkillSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'technical_skill_sections',
            },
        ),
    ]
