# Generated by Django 6.0.2 on 2026-03-17 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userexperiencesubsection_usertechnicalskill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexperiencesubsection',
            name='name',
            field=models.CharField(blank=True, default='Add your experience working on this project', max_length=100),
        ),
        migrations.AlterField(
            model_name='usertechnicalskill',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usertechnicalskillsection'),
        ),
        migrations.CreateModel(
            name='UserProfileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='users/profile_pictures/sbcf-default-avatar.png', null=True, upload_to='users/profiles/%Y/%m/%d/')),
                ('background_picture', models.ImageField(blank=True, default='users/background_pictures/sbcf-default-backgrounds.png', null=True, upload_to='users/background_pictures/%Y/%m/%d/')),
                ('biography', models.CharField(default='Welcome to my profile!', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_datas',
            },
        ),
    ]
