# Generated by Django 6.0.2 on 2026-03-27 21:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('request_type', models.CharField(choices=[('friend', 'friend'), ('project', 'project')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('declined', 'declined'), ('accepted', 'accepted')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'requestss',
                'constraints': [models.CheckConstraint(condition=models.Q(('request_type__in', ['friend', 'project'])), name='check_valid_request_type'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'declined', 'accepted'])), name='check_valid_status')],
            },
        ),
    ]
