# Generated by Django 6.0.2 on 2026-03-30 17:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='userrequest',
            name='pk',
            field=models.CompositePrimaryKey('sender_id', 'receiver_id', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='receiver',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='request_receiver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrequest',
            name='sender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='request_sender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now),
        ),
        migrations.AlterModelTable(
            name='userrequest',
            table='requests',
        ),
    ]
