# Generated by Django 6.0.2 on 2026-04-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttaskparticipation',
            options={},
        ),
    ]
