# Generated by Django 6.0.2 on 2026-03-28 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrole',
            name='project',
        ),
    ]
