# Generated by Django 6.0.2 on 2026-03-30 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_projectrole_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdomain',
            options={},
        ),
    ]
