# Generated by Django 6.0.2 on 2026-04-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projecttaskparticipation_task_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projecttaskparticipation',
            options={'managed': False},
        ),
    ]
