# Generated by Django 6.0.2 on 2026-04-11 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectdomain_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequirementSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Choose a new skill section(Frontend/Backend/Database etc..)', max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'db_table': 'project_requirements_sections',
            },
        ),
        migrations.CreateModel(
            name='ProjectSkillRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Choose a new required skill (Java/Aws/ChatGPT ...)', max_length=50)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectrequirementsection')),
            ],
            options={
                'db_table': 'project_skill_requirements',
            },
        ),
    ]
