# Generated by Django 6.0.2 on 2026-03-13 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 13, 13, 3, 36, 476526)),
        ),
    ]
