# Generated by Django 6.0.2 on 2026-03-17 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 17, 19, 12, 19, 165502)),
        ),
    ]
